### ISSUE TITLE
Build failed with GCC 4.8.4 on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by ln1equals0** [plstcharles/litiv#11]
Hi, I was trying to build with GCC 4.8.4 on Ubuntu 14.04
![2016-11-12 7 59 23](https://cloud.githubusercontent.com/assets/10298708/20240192/a058af22-a912-11e6-871c-29d24772597d.png)

When I try to make, there was following error
![2016-11-12 8 00 42](https://cloud.githubusercontent.com/assets/10298708/20240199/cfa5aa8c-a912-11e6-9466-f424d71e3d85.png)

How can fix I it? Thanks

**Comment by plstcharles** [comment]
Some of the types now used in the framework rely on C++14 features, so make sure your GCC version supports those. In this case, the error comes from the 'enable_if_t' helper type that was added in C++14, and was eventually patched in GCC around 4.8-4.9 (I don't quite remember the exact version).

Getting GCC to accept those helper types is easy, but some other C++14 features being used (especially related to constexpr) might not be easy to get working on older GCC versions, and that might force you to use an older version of the code. I pretty much gave up on GCC 4.8/C++11 compatibility when I moved to Ubuntu 16.04, unfortunately (now, C++14 is my baseline).

You could try to install GCC 5.0 on Ubuntu 14.04 -- I believe that would fix your issues. On the other hand, if you really need to get the code working with GCC 4.8, I can dig a little deeper and try to bring back the 'C++11' compatibility.

**Comment by ln1equals0** [comment]
Yeah, with GCC 5.4 the issue is fixed! Thanks!
