### ISSUE TITLE
How can I skip the bg model update？

### ISSUE THREAD

**Issue by Adwardyang** [plstcharles/litiv#18]
Hello，I‘m still study your PAWCS，I want to find a way to skip the bg model update，but I’m getting in trouble with the code......I use the PAWCS with bgslibrary，can you give me some annotations about the function “void BackgroundSubtractorPAWCS::apply()”? or some simple explain of the Looping statements？Please，need your help

**Comment by plstcharles** [comment]
Hello again --- I'll try to dust off the code in the next few days and highlight exactly where the updates are taking place. I can't guarantee that the code here 100% matches the one of bgslib (it's been forked a long time ago), but most lines should still overlap.

I'll try to update you within a few days!

**Comment by Adwardyang** [comment]
Really appreciated for your help， thanks so much！！

**Comment by plstcharles** [comment]
Alright, below is a unified diff I got after adding a few comments in the code related to the update mechanisms. The file should apply cleanly as a patch on the current version of this repo's "master" branch.

[pawcs-comments.txt](https://github.com/plstcharles/litiv/files/3523099/pawcs-comments.txt)

I hope it will help you!

**Comment by Adwardyang** [comment]
Thank you very much!!! I will go on
