### ISSUE TITLE
Compile error using MSVS 2015

### ISSUE THREAD

**Issue by ln1equals0** [plstcharles/litiv#7]
Hi when I compile the code in Visual Studio 2015 after cmake

![1](https://cloud.githubusercontent.com/assets/10298708/20150268/3e5944b2-a6b5-11e6-83f7-f1e21c4ec11b.jpg)

 I get 2 types of errors
1. "illegal indrection" in LBSP.hpp file
 
![4](https://cloud.githubusercontent.com/assets/10298708/20150195/dc8ffa14-a6b4-11e6-8933-e60a9dbd2b94.jpg)

![2](https://cloud.githubusercontent.com/assets/10298708/20150160/b3bf5ad0-a6b4-11e6-906f-ba1207ee864e.jpg)

2. some functions or variables are not member of cv

![3](https://cloud.githubusercontent.com/assets/10298708/20150220/fd029f18-a6b4-11e6-9f93-091779f2e621.jpg)
 

Any idea how to fix it?

**Comment by plstcharles** [comment]
Hello!

For the second error, it seems the handregistr app is missing a header include (opencv2/calib3d.hpp), adding it to 'main.cpp' should fix it (it works on my end without it however, I will retest this later today and patch the master branch accordingly).

For the first error, it feels like MSVC2015 is acting up around constant expressions again, as there are no dereferencing/indirection operations on that line (and C2100 is just about that). What MSVC2015 build/update version are you using? Again, I'll try to replicate the problem later this afternoon (no MSVC2015 where I am at the moment).

Thanks for the report!

-PLSTC

**Comment by plstcharles** [comment]
Update: I fixed the 2nd issue (missing include) in the master branch, but could not reproduce the first issue (C2100 on constexpr) using MSVC2015 Community or Enterprise (both with Update 3).

**Comment by ln1equals0** [comment]
Thanks! I was using MSVC2015 Update 1, after update to Update 3, the first error is also gone. 

Now the build is succeed.
